### ISSUE TITLE
How to start with this gem on heroku?

### ISSUE THREAD

**Issue by shyammohankanojia** [wpeterson/heroku-vector#3]
HI 

i followed all ur steps but it did not worked.

Please suggest How to start with this gem on heroku?

**Comment by wpeterson** [comment]
Follow the steps in the README file on the front page, from the Installation section.

**Comment by taylorbrooks** [comment]
@wpeterson Will adding `vector: heroku_vector -c config/heroku_vector.rb` to your Procfile automatically start a dyno running vector? Or is that something that needs to be done manually?

Am I correct in assuming that there needs to be a single dyno running vector?

**Comment by wpeterson** [comment]
Vector is a daemon process that needs to be running to sample your traffic and then automatically scale up or down other Heroku dynos.

There's an example Procfile you can check out, which adds a new dyno type that runs a Heroku Vector process:

https://github.com/wpeterson/heroku-vector/blob/master/examples/Procfile

You will need to install the heroku-vector gem in your Rails app and setup a configuration file as described.

**Comment by taylorbrooks** [comment]
Right, so installed the gem and added the line to the Procfile, deployed it. I would've expected a Vector dyno automatically start up and it didn't, that's all I was saying... 

<img width="883" alt="screen shot 2015-07-03 at 6 42 25 pm" src="https://cloud.githubusercontent.com/assets/117657/8505665/68d85d0a-21b3-11e5-9407-7b10b6918fb2.png">

**Comment by wpeterson** [comment]
OK, so it looks like you have a Procfile with multiple dyno types running.  I don't recognize the UI you're cutting and pasting from, but if you want to send me the output of running:

heroku ps 

I can try to help you get a vector dyno running.  You can email me or IM me on gchat at winfield.peterson@gmail.com.

**Comment by shyammohankanojia** [comment]
I don't know, some how It does not worked for me. I tried all the way @wpeterson given in the documents.
Finaly used https://addons.heroku.com/adept-scale 
with the starting plan, it worked.

**Comment by wpeterson** [comment]
This is an open source project that allows you to build and configure your own auto scaling for Heroku.

This is not a business or a service, so if you want someone to provide this for you then you should use a Heroku Addon or other service.

**Comment by fagiani** [comment]
@shyammohankanojia not sure if it is too late but I guess all you need to do after pushing the app with the gem and Procfile suggested on README is to get the vector dynos up by triggering something like this on the console:

`heroku ps:scale vector=1`

or by going to the heroku's admin UI (as printed above by @taylorbrooks) and scaling up the dyno slider for vector.
