### ISSUE TITLE
DynoScaler not printing logs...

### ISSUE THREAD

**Issue by taylorbrooks** [wpeterson/heroku-vector#5]
I'm not seeing any output when I tail the log for the vector process. If I use the Sidekiq source and set the period to 5 seconds, I would expect to see log output (using debug level) every 5 seconds. 

Assuming this `evaluate_and_scale` method is being called: https://github.com/wpeterson/heroku-vector/blob/master/lib/heroku_vector/dyno_scaler.rb#L67

My guess is 2 things:
1) EventMachine is not running or the periodic timer is not running. https://github.com/wpeterson/heroku-vector/blob/master/lib/heroku_vector/worker.rb#L35
2) EM is running but, the logs aren't being output correctly...

I'm thinking it's 1, because I queued up 10k jobs in Sidekiq and the worker dynos didn't scale up.

Investigating further...

**Comment by taylorbrooks** [comment]
Actually it looks like the logs are printing... but only every 10 minutes. So maybe something with the [PeriodicTimer](https://github.com/wpeterson/heroku-vector/blob/master/lib/heroku_vector/worker.rb#L34) is set up incorrectly. 

I'm not sure what `min_scale_time_secs` is, but maybe that has something to do with it??

<img width="824" alt="screen shot 2015-07-04 at 10 55 32 am" src="https://cloud.githubusercontent.com/assets/117657/8508573/4fc24e1a-223b-11e5-991c-bf9ba146566c.png">

**Comment by wpeterson** [comment]
The heroku_vector daemon uses standard ruby Logger and log level classes.  The default log level is info.  However, you can change the log level to debug if you want to see all events.

The evaluate_and_scale method that samples the data on each event loop only outputs in debug log levels.  By default, the only output logged is when the daemon takes action to scale up or down.

You can add the `--loglevel debug` command line parameter to see these messages.  For a full list of command line configuration, you can run the `--help` option:

``` bash
> heroku_vector --help
heroku_vector: auto-scale dynos on Heroku

  Usage: heroku_vector [options]
         heroku_vector -s

    -s, --sample                     Sample values and exit
    -d, --daemonize                  Daemonize process
    -e, --envfile PATH               Environment file (default: .env)
    -c, --config PATH                Config file (default: config.rb)
    -p, --pidfile PATH               Daemon pid file (default: heroku_vector.pid)
    -x, --loglevel LEVEL             Logging level [fatal/warn/info/debug] (default is info)
    -l, --logfile PATH               Logfile path for daemon
    -h, --help                       Show this message
```

**Comment by taylorbrooks** [comment]
See first comment, I've been using `debug` loglevel

**Comment by wpeterson** [comment]
Also, the log output you're showing shows 0 busy Sidekiq threads.  It sounds like you're trying to autoscale your sidekiq workers but perhaps you aren't pulling the right data from Sidekiq.

Did you configure both the Sidekiq Redis URL and namespace?  Most Sidekiq installation wrap their data in a namespace and using a different namespace will cause meta data like the number of busy workers to be read incorrectly (as 0).

You can test out the configuration you have using the sample mode, with the command line option `-s` which will load up a scaler and configuration but just print out one round of data samples.

**Comment by wpeterson** [comment]
Also, Heroku may be caching/delaying the log output from the dyno to you which could make configuring and debugging on a dyno difficult.

Perhaps you should try running vector locally on your machine while you are modifying the configuration and scaling until it's running the way you want, then deploy it to a dyno.

When you're running it locally, it can be helpful to populate your environment config in an environment file.  You can tell heroku vector to run with that config via the `-e /path/to/your.env`.

**Comment by taylorbrooks** [comment]
I did not have the name space configured, did that. How can I tell Sidekiq is actually using that namespace?

**Comment by wpeterson** [comment]
You just need to pass the Sidekiq data source the redis configuration you are already passing to Sidekiq.  This is probably being done in `config/initializers/sidekiq.rb` file within your Rails app.  The only two values that matter are the Redis Server URL and Redis Namespace.

You will know you are connected to your Sidekiq data properly when you can sample non 0 values for the number of busy workers.

**Comment by taylorbrooks** [comment]
Yeah did all that, still not working... :(

**Comment by taylorbrooks** [comment]
@wpeterson What's the difference between `period` and `min_scale_time_secs`? And how do those play together?

**Comment by wpeterson** [comment]
`period` is for the sampler, it controls the period with which you pull sample data.  For NewRelic you can't get data in smaller than one minute intervals.  For Sidekiq, it's close to realtime.

The `min_scale_time_secs` config option controls how often the dyno scaler will scale the dynos.  It is hard-coded to 5 minutes right now and that config value does not take precedence.  If you need to change this I can wire it up and push a new release.

It provides a buffer so that there is less thrashing up and down if your traffic fluctuates dramatically over a short period of time.  This means if the data show you need to scale up, it will scale up now, but not scale up or down again until 5 minutes have passed.

**Comment by taylorbrooks** [comment]
Gotcha, thanks for the explanation. I got it working, threw 20k jobs at Sidekiq and vector spooled up 3 new instances. Awesome.

Still no log output on `debug` loglevel.

One clarification, these are my settings:

``` ruby
HerokuVector.configure do |config|                 
  config.add_dyno_scaler('worker', {               
    source:         HerokuVector::Source::Sidekiq, 
    period:         5,                             
    min_dynos:      1,                             
    max_dynos:      7,                             
    min_value:      0.5,                           
    max_value:      4,                             
    scale_up_by:    3
  })                                               
end
```

My `scale_up_by` is 3 (default `scale_down_by` is 1 and `min_scale_time_secs` is 300); will it take 15 minutes for all my workers to scale back down to zero?

**Comment by wpeterson** [comment]
Taylor - congrats, I'm glad to hear you got it working.  If you have suggestions about how to make the documentation or configuration easier, I'd love to hear it.

Yes, with scale_up_by => 3 and you got a big spike of traffic:
Minute 0: 1 dyno
Traffic goes up
Minute 1: 4 dynos (+3)
Traffic comes back down
Minute 6: 3 dynos (-1)
Minute 11: 2 dynos (-1)
Minute 16: 1 dyno (-1)

You can control the velocity of scaling up and scaling down to meet your needs.
